import { writeFile } from 'node:fs/promises';
import { products, imagePath, money } from '../assets/catalog.js';

const escape = (text) => String(text).replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const iconPaths = {
  arrow: '<path d="M4 12h15M13 6l6 6-6 6"/>',
  diagonal: '<path d="M5 19 19 5M5 5h14v14"/>',
  down: '<path d="M12 4v16M6 14l6 6 6-6"/>',
  close: '<path d="m6 6 12 12M18 6 6 18"/>',
  plus: '<path d="M12 5v14M5 12h14"/>',
  minus: '<path d="M5 12h14"/>',
  bag: '<path d="M6 7h12l2 13H4L6 7ZM9 8V6a3 3 0 0 1 6 0v2"/>',
  menu: '<path d="M3 8h18M3 16h18"/>',
  chevron: '<path d="m9 6 6 6-6 6"/>',
  expand: '<path d="M4 9V4h5M15 4h5v5M20 15v5h-5M9 20H4v-5"/>'
};
const icon = (name) => `<svg viewBox="0 0 24 24" aria-hidden="true">${iconPaths[name]}</svg>`;
const img = (name, alt, attrs = '') => `<img src="${imagePath(name)}" alt="${escape(alt)}" width="832" height="1248" ${attrs}>`;
const card = (p) => `<article class="product-card" data-product="${p.id}" data-category="${p.category}" data-price="${p.price}">
  <div class="product-image-link"><a href="${p.id}.html" aria-label="View ${escape(p.name)}">${img(p.image, p.alt, 'loading="lazy" class="card-main-image"')}${img(p.scene, p.sceneAlt, 'loading="lazy" class="hover-image"')}</a>
    ${p.id === 'full-kit' ? '<span class="product-card-tag">Three-piece set</span>' : ''}
    <button class="card-add" data-quick="${p.id}" aria-label="Choose size for ${escape(p.name)}">${icon('plus')}</button>
  </div>
  <div class="card-info"><div><h3><a href="${p.id}.html">${escape(p.name)}</a></h3><p>${escape(p.color)}</p></div><span class="card-price">${money(p.price)}</span></div>
  ${p.id === 'full-kit' ? '<p class="card-image-note">Hoodie + joggers + tee. Hoodie shown.</p>' : ''}
</article>`;
const filterButtons = (includeSets = true) => `<div class="filter-list" role="group" aria-label="Filter products">${['All', 'Tops', 'Outerwear', 'Accessories', ...(includeSets ? ['Sets'] : [])].map((x) => `<button data-filter="${x}" aria-pressed="${x === 'All'}">${x === 'All' ? 'All pieces' : x}</button>`).join('')}</div>`;
const viewSwitch = () => '<div class="view-switch" role="group" aria-label="Product image style"><button data-view="studio" aria-pressed="true">Studio</button><button data-view="scene" aria-pressed="false">Styled</button></div>';
const brand = `<a class="brand" href="index.html" aria-label="SUL home"><img src="assets/images/sul-wordmark.png" width="180" height="100" alt="SUL"><span class="brand-name">Snooze<br>U Lose</span></a>`;
function header(active) { return `<a class="skip-link" href="#main">Skip to content</a>
<header class="site-header">${brand}<nav class="desktop-nav" aria-label="Main navigation"><a href="collections.html"${active === 'collections' ? ' aria-current="page"' : ''}>Shop all</a><a href="index.html#studio">The studio</a><a href="index.html#story">Our world</a></nav><div class="header-actions"><button class="bag-trigger" data-open="bag-dialog" aria-label="Open shopping bag">${icon('bag')}<span>Bag</span><span class="bag-count">(0)</span></button><button class="menu-trigger" data-open="menu-dialog" aria-label="Open navigation">Menu${icon('menu')}</button></div></header>`; }
const footer = `<footer class="site-footer shell"><div class="footer-top"><h2>Don’t sleep<br>on what’s next.</h2><nav class="footer-nav" aria-label="Footer navigation"><a href="collections.html">Shop the collection</a><a href="index.html#studio">The studio</a><a href="https://www.instagram.com/snoozeulose/" target="_blank" rel="noopener noreferrer">Instagram${icon('diagonal')}</a><a href="https://www.tiktok.com/@snoozeulose" target="_blank" rel="noopener noreferrer">TikTok${icon('diagonal')}</a></nav></div><div class="footer-wordmark"><img src="assets/images/sul-wordmark.png" width="608" height="338" loading="lazy" alt="SUL"><p class="footer-credo">Snooze.<br>You lose.</p></div><div class="footer-bottom"><p>© ${new Date().getUTCFullYear()} SUL — Snooze U Lose.</p><p>Checkout is in test mode.</p></div></footer>`;
const dialogs = `<dialog id="bag-dialog" class="bag-dialog" aria-labelledby="bag-title"><div class="dialog-head"><h2 id="bag-title">Your bag <span id="bag-heading-count">(0)</span></h2><button class="dialog-close" data-close aria-label="Close bag">${icon('close')}</button></div><div class="bag-items" id="bag-items"></div><div class="bag-foot"><div class="bag-subtotal"><span>Subtotal</span><strong id="bag-total">$0</strong></div><button class="button wine" id="preview-checkout" disabled>Preview checkout${icon('arrow')}</button><div class="preview-links" id="preview-links" hidden></div><p id="bag-note">Payments are in test mode. Your bag is saved on this device.</p></div></dialog>
<dialog id="quick-dialog" class="quick-dialog" aria-labelledby="quick-title"><div class="dialog-head"><h2 id="quick-title">Make it yours.</h2><button class="dialog-close" data-close aria-label="Close size selector">${icon('close')}</button></div><div id="quick-content"></div></dialog>
<dialog id="image-dialog" class="image-dialog" aria-label="Enlarged product image"><button class="dialog-close" data-close aria-label="Close image">${icon('close')}</button><img src="assets/images/hoodie.webp" alt="" id="enlarged-image"></dialog>
<dialog id="menu-dialog" class="menu-dialog" aria-label="Site navigation"><div class="dialog-head">${brand}<button class="dialog-close" data-close aria-label="Close navigation">${icon('close')}</button></div><nav class="mobile-links"><a href="collections.html">Shop all${icon('diagonal')}</a><a href="index.html#studio">The studio${icon('diagonal')}</a><a href="index.html#story">Our world${icon('diagonal')}</a><a href="https://www.instagram.com/snoozeulose/" target="_blank" rel="noopener noreferrer">Instagram${icon('diagonal')}</a></nav><p class="menu-note">SUL — Snooze U Lose. Don’t sleep on style.</p></dialog><div id="toast" class="toast" role="status" hidden></div>`;
function document({ title, description, path, body, active = '', bodyClass = '', product }) {
  const url = `https://snoozeulose.com/${path === 'index.html' ? '' : path}`;
  const image = product ? imagePath(product.image) : imagePath('technical-study');
  const ld = product ? { '@context': 'https://schema.org', '@type': 'Product', name: product.name, image: `https://snoozeulose.com/${image}`, description: product.description, brand: { '@type': 'Brand', name: 'SUL — Snooze U Lose' } } : { '@context': 'https://schema.org', '@type': path === 'collections.html' ? 'CollectionPage' : 'WebSite', name: 'SUL — Snooze U Lose', url };
  return `<!doctype html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${escape(title)}</title><meta name="description" content="${escape(description)}"><meta name="theme-color" content="#111315"><link rel="canonical" href="${url}"><meta property="og:title" content="${escape(title)}"><meta property="og:description" content="${escape(description)}"><meta property="og:type" content="${product ? 'product' : 'website'}"><meta property="og:url" content="${url}"><meta property="og:image" content="https://snoozeulose.com/${image}"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="assets/images/sul-wordmark.png"><link rel="preload" href="assets/fonts/barlow-condensed-800.ttf" as="font" type="font/ttf" crossorigin><link rel="preload" href="assets/fonts/manrope-400.ttf" as="font" type="font/ttf" crossorigin><link rel="stylesheet" href="assets/style.css"><script type="application/ld+json">${JSON.stringify(ld).replace(/</g, '\\u003c')}</script><script type="module" src="assets/site.js"></script></head><body class="${bodyClass}">${header(active)}${body}${footer}${dialogs}</body></html>\n`.replace(/[ \t]+\n/g, '\n');
}

const home = `<main id="main">
<section class="hero" aria-labelledby="hero-title"><div class="hero-copy"><h1 id="hero-title"><span>Don’t<br class="desktop-break"> sleep</span><br class="desktop-break"><span class="last-line">on style.</span></h1><p>For the ones who move on their own time.<br>Streetwear with something to say.</p><a href="collections.html" class="button light">Explore the collection${icon('arrow')}</a><div class="hero-bottom"><span>Snooze U Lose. A state of mind.</span>${icon('down')}</div></div><div class="hero-visual">${img('technical-study', 'SUL technical collection design study: black hooded outfit with chrome logos and blue detailing', 'class="hero-photo" fetchpriority="high"')}<span class="hero-image-caption">Design preview — SUL studio</span><a href="#studio" class="hero-feature">${img('crown-hoodie-sample', 'SUL crown hoodie sample in charcoal', 'loading="eager"')}<div><strong>The crown. Reimagined.</strong><small>Hoodie sample · Explore the studio</small></div>${icon('diagonal')}</a></div></section>
<div class="brand-strip"><span class="strip-name">Snooze U Lose</span><span class="strip-rule"></span><span>Wear your own ambition.</span><span class="strip-rule"></span><span class="strip-extra">Don’t sleep on style.</span></div>
<section id="collection" class="collection-section shell" data-shop><div class="section-heading"><h2>Your next<br>rotation.</h2><p>Signature layers. Everyday statements.<br>Find the piece that feels like you.</p></div><div class="display-controls">${filterButtons(false)}${viewSwitch()}</div><div class="product-grid">${products.slice(0, 4).map(card).join('')}</div><p class="shop-empty" hidden>No pieces in this selection. Explore all pieces.</p><div class="collection-bottom"><a class="button" href="collections.html">Shop all pieces${icon('arrow')}</a></div></section>
<section id="studio" class="studio-section"><div class="studio-heading shell"><h2>The next<br>wake-up call.</h2><div><p>Chrome. Crown. A new kind of SUL.</p><p class="studio-disclaimer">A look inside the design studio. These designs are previews.</p></div></div><div class="studio-stage"><div class="studio-main">${img('chrome-study', 'SUL design study showing chrome logos, blue detailing, a bomber, sweater, jersey, and cargo trousers', 'id="studio-image" loading="lazy"')}</div><div class="studio-selector"><button aria-pressed="true" data-study="chrome-study" data-study-alt="SUL design study showing chrome logos, blue detailing, a bomber, sweater, jersey, and cargo trousers"><span>Chrome & blue</span>${icon('arrow')}</button><button aria-pressed="false" data-study="essentials-study" data-study-alt="SUL essentials design study with a washed black zip hoodie, cream tee, black varsity jacket, and wide leg trousers"><span>After-hours essentials</span>${icon('arrow')}</button><button aria-pressed="false" data-study="technical-study" data-study-alt="SUL technical clothing design study with black outfits, logo tee, bag, and cap"><span>Technical collection</span>${icon('arrow')}</button></div></div><div class="studio-sample shell"><div class="sample-image">${img('crown-hoodie-sample', 'Rear view of a charcoal SUL hoodie sample with a blue and chrome crown logo', 'loading="lazy"')}</div><div class="sample-copy"><h3>A new mark.<br>The same mindset.</h3><p>The crown enters the picture. A closer look at the next SUL direction, from design studies to a hoodie sample.</p><span class="small-label">From the studio</span></div></div></section>
<section id="print-edit" class="print-edit shell"><div class="section-heading"><h2>Make some<br>noise.</h2><p>From all-over clocks to bold SUL lettering.<br>A closer look at the printed sets.</p></div><div class="print-grid">${[
  ['snooze-shirt', 'snooze-shorts', 'Snooze U Lose', 'White / Red / Black', 'White short sleeve SUL button-up shirt with repeating red and black lettering'],
  ['time-shirt', 'time-shorts', 'Time is money', 'White / Black / Gold', 'White short sleeve shirt with clock artwork and Stop Wasting lettering'],
  ['abstract-shirt', 'abstract-shorts', 'Outside the lines', 'Blue / Grey / White', 'SUL short sleeve shirt with blue and grey abstract line artwork'],
  ['alarm-shirt', 'alarm-shorts', 'Wake-up call', 'Charcoal / Lime', 'Charcoal short sleeve shirt with repeating lime digital alarm clock artwork'],
  ['money-shirt', 'money-shorts', 'Make your move', 'Black / Multicolor', 'Black SUL short sleeve shirt with banknote graphics and lettering']
].map(([shirt, shorts, name, color, alt]) => `<article class="print-card"><button class="print-image" data-enlarge="${shirt}" data-alt="${escape(alt)}" aria-label="Enlarge ${escape(name)} shirt">${img(shirt, alt, 'loading="lazy"')}${icon('expand')}</button><div class="print-info"><h3>${name}</h3><span>${color}</span></div><div class="print-controls" role="group" aria-label="${name} image"><button data-print-image="${shirt}" data-print-alt="${escape(alt)}" aria-pressed="true">Shirt</button><button data-print-image="${shorts}" data-print-alt="Matching ${escape(name)} printed drawstring shorts" aria-pressed="false">Shorts</button></div></article>`).join('')}</div><p class="print-note">Shown from the SUL studio. Product availability and pricing to be announced.</p></section>
<section class="campaign" id="lookbook"><div class="campaign-image">${img('city', 'SUL white and maroon sweatsuit worn on a city street', 'id="campaign-image" loading="lazy"')}<span class="campaign-caption" id="campaign-caption">SUL in the city.</span></div><div class="campaign-copy"><div class="campaign-tabs" role="group" aria-label="Lookbook setting"><button data-campaign="city" aria-pressed="true">In the city</button><button data-campaign="outdoor" aria-pressed="false">Off the clock</button></div><h2>Different<br>hours.<br>Same energy.</h2><p>Out in the city. Off the clock. Wherever the day takes you, bring your own point of view.</p><a class="campaign-link" href="collections.html">Find your everyday uniform${icon('arrow')}</a></div></section>
<section class="manifesto shell" id="story"><h2>More than<br>a name.<br>A mindset.</h2><div class="manifesto-copy"><p><strong>Snooze U Lose.</strong> A reminder to go after what matters. To show up as yourself. To make your next move count.</p><p>From the lion to the crown, that’s the thread running through SUL. The rest is how you wear it.</p><a class="text-link" href="https://www.instagram.com/snoozeulose/" target="_blank" rel="noopener noreferrer">Step inside our world${icon('diagonal')}</a></div></section>
</main>`;

const collection = `<main id="main" class="collection-page"><section class="collection-hero shell"><h1>The collection.</h1><p class="collection-intro">The SUL signatures. Layers, statement pieces, and the finishing touch.</p></section><section class="collection-section shell" data-shop><h2 class="sr-only">Browse SUL products</h2><div class="browse-tools">${filterButtons()}<label class="sort-label">Sort by<select id="sort-products"><option value="featured">Featured</option><option value="price-low">Price: low to high</option><option value="price-high">Price: high to low</option></select></label></div><div class="display-controls"><p class="collection-count" aria-live="polite" id="collection-count">5 pieces</p>${viewSwitch()}</div><div class="product-grid">${products.map(card).join('')}<aside class="collection-cta"><h2>Next up.<br>Stay awake.</h2><div><p>Step inside the SUL design studio.</p><a href="index.html#studio" class="text-link">Explore what’s next${icon('arrow')}</a></div></aside></div><p class="shop-empty" hidden>No pieces in this selection. Explore all pieces.</p></section></main>`;
const sizeOptions = (p) => `<fieldset class="size-fieldset"><legend>Select your size</legend><div class="size-options" role="group" aria-label="Size for ${escape(p.name)}">${p.sizes.map((s) => `<button type="button" data-size="${escape(s)}" aria-pressed="${p.sizes.length === 1}"${p.sizes.length === 1 ? ' class="selected"' : ''}>${escape(s)}</button>`).join('')}</div><p class="inline-error" role="status" id="size-error"></p></fieldset>`;
const productPage = (p) => `<main id="main"><nav class="breadcrumb" aria-label="Breadcrumb"><a href="index.html">Home</a>${icon('chevron')}<a href="collections.html">The collection</a>${icon('chevron')}<span aria-current="page">${escape(p.name)}</span></nav><div class="product-layout shell"><section class="product-gallery" aria-label="${escape(p.name)} gallery"><div class="gallery-main">${img(p.image, p.alt, 'id="gallery-image" fetchpriority="high"')}<button class="gallery-enlarge" data-enlarge="${p.image}" data-alt="${escape(p.alt)}" aria-label="Enlarge product image">${icon('expand')}</button></div><div class="gallery-thumbs" role="group" aria-label="Choose product image">${p.gallery.map((im, i) => `<button data-gallery="${im}" data-gallery-alt="${escape(i === 0 ? p.alt : p.sceneAlt)}" aria-pressed="${i === 0}" aria-label="${i === 0 ? 'Studio view' : 'Alternate view'}">${img(im, i === 0 ? p.alt : p.sceneAlt, 'loading="lazy"')}</button>`).join('')}</div>${p.imageNote ? `<p class="image-note">${escape(p.imageNote)}</p>` : ''}</section><section class="product-summary" data-detail="${p.id}" aria-labelledby="product-title"><h1 id="product-title">${escape(p.name)}</h1><div class="product-price-row"><strong>${money(p.price)}</strong><span class="color-name"><span class="color-swatch" aria-hidden="true"></span>${escape(p.color)}</span></div><p class="product-description">${escape(p.description)}</p>${sizeOptions(p)}<button class="button wine product-add" data-add="${p.id}"><span>Add to bag — ${money(p.price)}</span>${icon('plus')}</button><p class="product-preview-note">Saved to your bag on this device.<br>Checkout is currently in test mode. <a href="${p.checkout}" target="_blank" rel="noopener noreferrer">Open test checkout</a>.</p><dl class="product-details">${p.details.map(([key, value]) => `<div><dt>${escape(key)}</dt><dd>${escape(value)}</dd></div>`).join('')}</dl></section></div><section class="related shell"><div class="section-heading"><h2>Keep the energy.</h2><a class="text-link" href="collections.html">See all${icon('arrow')}</a></div><div class="product-grid">${products.filter((x) => x.id !== p.id).slice(0, 3).map(card).join('')}</div></section></main>`;

await writeFile('index.html', document({ title: 'SUL — Snooze U Lose | Don’t Sleep On Style', description: 'Step inside SUL. Signature streetwear, everyday layers, and a look into the next design direction. Don’t sleep on style.', path: 'index.html', body: home }));
await writeFile('collections.html', document({ title: 'The Collection | SUL — Snooze U Lose', description: 'Explore the SUL collection: Blackout Hoodie, Bomber Jacket, Lion Sweater, New Era Trucker Hat, and the Full Kit.', path: 'collections.html', body: collection, active: 'collections' }));
for (const p of products) await writeFile(`${p.id}.html`, document({ title: `${p.name} | SUL — Snooze U Lose`, description: p.description, path: `${p.id}.html`, body: productPage(p), product: p }));
await writeFile('404.html', document({ title: 'Find Your Way Back | SUL', description: 'Find your way back to the SUL collection.', path: '404.html', body: `<main id="main" class="not-found shell"><h1>Missed the turn.</h1><p>This page isn’t here. Your next piece is still waiting in the collection.</p><a class="button wine" href="collections.html">Back to the collection${icon('arrow')}</a></main>` }));
console.log(`Built homepage, collection, ${products.length} product pages, and 404. Static files are ready to serve.`);
